%Display the result inspector
%Usage:
%    ZViewer( nTab )
%    Refer to user manual for detail GUI operation
%Parameters:
%    nTab: Tab index to be displayed:
%       1: AC voltage & current information
%       2: AC results (default).
%       3: DC voltage & current information
%       4: DC results.
%

VICTOGUI.diode_algorithm_on=0;

VICTOGUI.nTab=1;

    %Tab names
    VICTOGUI.szTabNames = {'Virtual Impedance Calculation', 'Stability Analysis'};

    %Create tabbed window
    %Note HSHEETPANELS is an array to the windows representing the tabs and
    %are indexed according to szTabNames, so HSHEETPANELS(3) is the handle to
    %the window that is associated with the tab called 'Current Result'
    %OnChangedSelTabs is the event handler that is called when the user
    %clicks on a different tab
    [VICTOGUI.HFIG, ~, VICTOGUI.HSHEETPANELS] = tabdlg(...
            'create',VICTOGUI.szTabNames,{},@OnChangedSelTabs,[ 1000, 650], [0,0,0,0], VICTOGUI.nTab);
   

    %Set parameters of main windows used in callback
    VICTOGUI.UserDataFig.szTabNames = VICTOGUI.szTabNames;
    VICTOGUI.UserDataFig.HSHEETPANELS = VICTOGUI.HSHEETPANELS;
    set(VICTOGUI.HFIG, 'UserData',VICTOGUI.UserDataFig);
     

    % Set windows name
    set(VICTOGUI.HFIG, 'Name', 'Boeing stability software suite');

    %Set window at middle of screen
    VICTOGUI.SCR = get( 0, 'ScreenSize' );
    VICTOGUI.FIG = get(VICTOGUI.HFIG,'Position');
    VICTOGUI.XPOS = [(VICTOGUI.SCR(3)-VICTOGUI.FIG(3))/2 (VICTOGUI.SCR(4)-VICTOGUI.FIG(4))/2 VICTOGUI.FIG(3) VICTOGUI.FIG(4)];
    set(VICTOGUI.HFIG,'Position',VICTOGUI.XPOS);
    set(VICTOGUI.HFIG,'Visible','on');
    clear VICTOGUI.SCR VICTOGUI.FIG;

    
    %% Construct User Interface
    %Select first tab
    %Virtual Impedance Calculation Tool
    VICTOGUI.hVICTO = VICTOGUI.HSHEETPANELS(1);



VICTOGUI.ha=axes('Parent',VICTOGUI.hVICTO,...
        'Position',[0.45 0.14 0.5 0.7],...
        'Box','on');

VICTOGUI.htx = uicontrol(VICTOGUI.hVICTO,...
                 'style','tex',...
                 'unit','normalized',...
                 'position',[0.45,0.9,0.5,0.06],...
                 'backgroundcolor',[0 0.8047 0.8164],...
                 'fontsize',11,'fontweight','bold',... 
                 'string','press ''specify model/system name'' and pick the model file to be simulated');

VICTOGUI.htx2 = uicontrol(VICTOGUI.hVICTO,...
                 'style','tex',...
                 'unit','normalized',...
                 'position',[0.05 0.02 0.3 0.06],...
                 'backgroundcolor',[0.8516 0.4375 0.8359],...
                 'fontsize',10,'fontweight','bold',... 
                 'string','Virtual Impedance Calculation Tool    Copyright © 2012 Boeing. All rights reserved.');


VICTOGUI.hlogo1=axes('Parent',VICTOGUI.hVICTO,'units','normalized','position',[0.05 0.75 0.3 0.25]);
uistack(VICTOGUI.hlogo1,'down');
VICTOGUI.logo1=imread('VICTO.png');
image(VICTOGUI.logo1)
colormap gray
set(VICTOGUI.hlogo1,'handlevisibility','off','visible','off');
             
             
VICTOGUI.htx4 = uicontrol(VICTOGUI.hVICTO,...
                 'style','tex',...
                 'unit','normalized',...
                 'position',[0.05 0.7 0.3 0.06],...
                 'backgroundcolor',[1.0000    1.0000    0.9375],...
                 'fontsize',11,'fontweight','bold',... 
                 'string','Perturbation frequencies table will be shown here after step 2');   

VICTOGUI.hedit1=uicontrol(VICTOGUI.hVICTO,...
           'Style','pushbutton',...
           'unit','normalized',...
           'Position',[0.05, 0.55, 0.3, 0.05],...
           'String','specify system/block name','Fontsize',12,'FontWeight','bold',...
           'Callback',...
           ['VICTOGUI.filenames1=uigetfile(''*.mdl'',''Select the MATLAB model file'');'...
           'VICTOGUI.filenames2=regexp(VICTOGUI.filenames1, ''\.mdl'', ''split'');'...
           'VICTOGUI.system_name_str=VICTOGUI.filenames2(1:1);'...
           'VICTOGUI.system_name_str=VICTOGUI.system_name_str{1};'...
           'VICTOGUI.block_name_file_id = fopen(VICTOGUI.filenames1);'...
           'VICTOGUI.string_model=fscanf(VICTOGUI.block_name_file_id,''%c'');'...
           'VICTOGUI.block_state=0;'...
           'VICTOGUI.block_name_index=findstr(VICTOGUI.string_model,''Three-Phase Impedance Analyzer\nShunt Current Single-tone L2L'');'...
           'if VICTOGUI.block_name_index>0;'...
           'VICTOGUI.block_state=1;'...
           'end;'...
           'VICTOGUI.block_name_index=findstr(VICTOGUI.string_model,''Three-Phase Impedance Analyzer\nShunt Current Single-tone P2N'');'...
           'if VICTOGUI.block_name_index>0;'...
           'VICTOGUI.block_state=2;'...
           'end;'...
           'VICTOGUI.block_name_index=findstr(VICTOGUI.string_model,''Three-Phase Impedance Analyzer\nShunt Current Multi-tone L2L'');'...
           'if VICTOGUI.block_name_index>0;'...
           'VICTOGUI.block_state=3;'...
           'end;'...
           'VICTOGUI.block_name_index=findstr(VICTOGUI.string_model,''Three-Phase Impedance Analyzer\nShunt Current Multi-tone P2N'');'...
           'if VICTOGUI.block_name_index>0;'...
           'VICTOGUI.block_state=4;'...'
           'end;'...
           'VICTOGUI.block_name_index=findstr(VICTOGUI.string_model,''Three-Phase Impedance Analyzer\nSeries Voltage Single-tone L2L'');'...
           'if VICTOGUI.block_name_index>0;'...
           'VICTOGUI.block_state=5;'...
           'end;'...
           'VICTOGUI.block_name_index=findstr(VICTOGUI.string_model,''Three-Phase Impedance Analyzer\nSeries Voltage Single-tone P2N'');'...
           'if VICTOGUI.block_name_index>0;'...
           'VICTOGUI.block_state=6;'...
           'end;'...
           'VICTOGUI.block_name_index=findstr(VICTOGUI.string_model,''Three-Phase Impedance Analyzer\nSeries Voltage Multi-tone L2L'');'...
           'if VICTOGUI.block_name_index>0;'...
           'VICTOGUI.block_state=7;'...
           'end;'...
           'VICTOGUI.block_name_index=findstr(VICTOGUI.string_model,''Three-Phase Impedance Analyzer\nSeries Voltage Multi-tone P2N'');'...
           'if VICTOGUI.block_name_index>0;'...
           'VICTOGUI.block_state=8;'...
           'end;'...
           'VICTOGUI.block_name_index=findstr(VICTOGUI.string_model,''DC Impedance Analyzer\nShunt Current Single-tone'');'...
           'if VICTOGUI.block_name_index>0;'...
           'VICTOGUI.block_state=9;'...
           'end;'...
           'VICTOGUI.block_name_index=findstr(VICTOGUI.string_model,''DC Impedance Analyzer\nShunt Current Multi-tone'');'...
           'if VICTOGUI.block_name_index>0;'...
           'VICTOGUI.block_state=10;'...
           'end;'...
           'VICTOGUI.block_name_index=findstr(VICTOGUI.string_model,''DC Impedance Analyzer\nSeries Voltage Single-tone'');'...
           'if VICTOGUI.block_name_index>0;'...
           'VICTOGUI.block_state=11;'...
           'end;'...
           'VICTOGUI.block_name_index=findstr(VICTOGUI.string_model,''DC Impedance Analyzer\nSeries Voltage Multi-tone'');'...
           'if VICTOGUI.block_name_index>0;'...
           'VICTOGUI.block_state=12;'...
           'end;'...
           'fclose(''all'');'...
           'if VICTOGUI.block_state==1;'...
           'VICTOGUI.block_name_str=strcat(VICTOGUI.system_name_str,''/Three-Phase Impedance Analyzer Shunt Current Single-tone L2L'');'...
           'elseif VICTOGUI.block_state==2;'...
           'VICTOGUI.block_name_str=strcat(VICTOGUI.system_name_str,''/Three-Phase Impedance Analyzer Shunt Current Single-tone P2N'');'...
           'elseif VICTOGUI.block_state==3;'...
           'VICTOGUI.block_name_str=strcat(VICTOGUI.system_name_str,''/Three-Phase Impedance Analyzer Shunt Current Multi-tone L2L'');'...
           'elseif VICTOGUI.block_state==4;'...
           'VICTOGUI.block_name_str=strcat(VICTOGUI.system_name_str,''/Three-Phase Impedance Analyzer Shunt Current Multi-tone P2N'');'...
           'elseif VICTOGUI.block_state==5;'...
           'VICTOGUI.block_name_str=strcat(VICTOGUI.system_name_str,''/Three-Phase Impedance Analyzer Series Voltage Single-tone L2L'');'...
           'elseif VICTOGUI.block_state==6;'...
           'VICTOGUI.block_name_str=strcat(VICTOGUI.system_name_str,''/Three-Phase Impedance Analyzer Series Voltage Single-tone P2N'');'...
           'elseif VICTOGUI.block_state==7;'...
           'VICTOGUI.block_name_str=strcat(VICTOGUI.system_name_str,''/Three-Phase Impedance Analyzer Series Voltage Multi-tone L2L'');'...
           'elseif VICTOGUI.block_state==8;'...
           'VICTOGUI.block_name_str=strcat(VICTOGUI.system_name_str,''/Three-Phase Impedance Analyzer Series Voltage Multi-tone P2N'');'...
           'elseif VICTOGUI.block_state==9;'...
           'VICTOGUI.block_name_str=strcat(VICTOGUI.system_name_str,''/DC Impedance Analyzer Shunt Current Single-tone'');'...
           'elseif VICTOGUI.block_state==10;'...
           'VICTOGUI.block_name_str=strcat(VICTOGUI.system_name_str,''/DC Impedance Analyzer Shunt Current Multi-tone'');'...
           'elseif VICTOGUI.block_state==11;'...
           'VICTOGUI.block_name_str=strcat(VICTOGUI.system_name_str,''/DC Impedance Analyzer Series Voltage Single-tone'');'...
           'elseif VICTOGUI.block_state==12;'...
           'VICTOGUI.block_name_str=strcat(VICTOGUI.system_name_str,''/DC Impedance Analyzer Series Voltage Multi-tone'');'...
           'else'...
           'VICTOGUI.block_name_str=''error'';'...
           'end;'...
           'set(VICTOGUI.htx,''string'',''system/block name specified'',''fontsize'',11);'...
           'VICTOGUI.block_name_str=VICTOGUI.block_name_str{1};']);             
              

VICTOGUI.hedit3 = uicontrol(VICTOGUI.hVICTO,...
                 'style','edit',...
                 'unit','normalized',...
                 'Position',[0.05, 0.49, 0.3, 0.05],...
                 'fontsize',11,...
                 'backgroundcolor',[1.0000    0.9792    0.8008],...
                 'string','impedance result file name','Fontsize',12,'FontWeight','bold');    
VICTOGUI.hinput = uicontrol(VICTOGUI.hVICTO,...
                 'style','push',...
                 'unit','normalized',...
                 'Position',[0.15, 0.43, 0.2, 0.05],...
                 'str','input filename','Fontsize',11,'FontWeight','bold',...
                 'Callback',...
                 'VICTOGUI.file_name_str=get(VICTOGUI.hedit3,''string'');');

VICTOGUI.check=uicontrol(VICTOGUI.hVICTO,...
           'Style','check',...
           'unit','normalized',...
           'Position',[0.05, 0.38, 0.3, 0.05],...
           'backgroundcolor',[1.0000    0.9708    0.8594],...
           'String','avoid diode frequency overlap','Fontsize',12,'FontWeight','bold','FontAngle','italic',...
           'Value',1,...
           'Callback',[...
           'if get(VICTOGUI.check,''Value'')==1;'...
           'VICTOGUI.diode_algorithm_on=1;'...
           'else;'...
           'VICTOGUI.diode_algorithm_on=0;'...
           'end;'...
           ]);
             
VICTOGUI.h1=uicontrol(VICTOGUI.hVICTO,...
           'Style','pushbutton',...
           'unit','normalized',...
           'Position',[0.05, 0.33, 0.3, 0.05],...
           'String','1:reach steady state','Fontsize',12,'FontWeight','bold',...
           'Callback',...
           ['set(VICTOGUI.htx,''string'',''1st simulation running'',''fontsize'',11);'...
           'if (VICTOGUI.block_state==1)|(VICTOGUI.block_state==2);'...
           'zac_stone_sci_1;'...
           'elseif (VICTOGUI.block_state==3)|(VICTOGUI.block_state==4);'...
           'zac_mtone_sci_1;'...
           'elseif (VICTOGUI.block_state==5)|(VICTOGUI.block_state==6);'...
           'zac_stone_svi_1;'...
           'elseif (VICTOGUI.block_state==7)|(VICTOGUI.block_state==8);'...
           'zac_mtone_svi_1;'...
           'elseif VICTOGUI.block_state==9;'...
           'zdc_stone_sci_1;'...
           'elseif VICTOGUI.block_state==10;'...
           'zdc_mtone_sci_1;'...
           'elseif VICTOGUI.block_state==11;'...
           'zdc_stone_svi_1;'...
           'else;'...
           'zdc_mtone_svi_1;'...
           'end;'...
           'set(VICTOGUI.htx,''string'', ''1st simulation done, voltage plotted to check steady state'',''fontsize'',11);']);
       
VICTOGUI.h2=uicontrol(VICTOGUI.hVICTO,...
           'Style','pushbutton',...
           'unit','normalized',...
           'Position',[0.05, 0.27, 0.3, 0.05],...
           'String','2:display perturbation frequency','Fontsize',12,'FontWeight','bold',...
           'Callback',...
           ['subplot(VICTOGUI.ha);'...
           'if (VICTOGUI.block_state==1)|(VICTOGUI.block_state==2);'...
           'zac_stone_sci_2;'...
           'elseif (VICTOGUI.block_state==3)|(VICTOGUI.block_state==4);'...
           'zac_mtone_sci_2;'...
           'elseif (VICTOGUI.block_state==5)|(VICTOGUI.block_state==6);'...
           'zac_stone_svi_2;'...
           'elseif (VICTOGUI.block_state==7)|(VICTOGUI.block_state==8);'...
           'zac_mtone_svi_2;'...
           'elseif VICTOGUI.block_state==9;'...
           'zdc_stone_sci_2;'...
           'elseif VICTOGUI.block_state==10;'...
           'zdc_mtone_sci_2;'...
           'elseif VICTOGUI.block_state==11;'...
           'zdc_stone_svi_2;'...
           'else;'...
           'zdc_mtone_svi_2;'...
           'end;'...
           'y_axis=ones(1,length(VICTO.fit));'...
           'semilogx(VICTO.fit,y_axis,''.r'');'...
           'xlabel(''frequency [Hz]'',''FontSize'',16);'...
           'title(''Perturbation frequencies [Hz]'',''FontSize'',16);'...
           'VICTOGUI.perturbation_table=uitable(VICTOGUI.hVICTO,''RowName'',''P_frequencies(Hz)'',''Data'',VICTO.fit,''unit'',''normalized'',''Position'',[0.05, 0.61, 0.3, 0.09]);'...
           'set(VICTOGUI.htx4,''string'', ''perturbation frequencies table'');'...
           'set(VICTOGUI.htx,''string'', ''perturbation frequencies displayed, if you need different perturbation frequencies, update fit and Ninj in the workspace and run step 2 again'',''fontsize'',9);']);
     
VICTOGUI.h3=uicontrol(VICTOGUI.hVICTO,...
           'Style','pushbutton',...
           'unit','normalized',...
           'Position',[0.05, 0.21, 0.3, 0.05],...
           'String','3:multiple simulation','Fontsize',12,'FontWeight','bold',...
           'Callback',...
           ['set(VICTOGUI.htx,''string'', ''multiple simulation running, perturbation injected'',''fontsize'',11);'...
           'if (VICTOGUI.block_state==1)|(VICTOGUI.block_state==2);'...
           'zac_stone_sci_3;'...
           'elseif (VICTOGUI.block_state==3)|(VICTOGUI.block_state==4);'...
           'zac_mtone_sci_3;'...
           'elseif (VICTOGUI.block_state==5)|(VICTOGUI.block_state==6);'...
           'zac_stone_svi_3;'...
           'elseif (VICTOGUI.block_state==7)|(VICTOGUI.block_state==8);'...
           'zac_mtone_svi_3;'...
           'elseif VICTOGUI.block_state==9;'...
           'zdc_stone_sci_3;'...
           'elseif VICTOGUI.block_state==10;'...
           'zdc_mtone_sci_3;'...
           'elseif VICTOGUI.block_state==11;'...
           'zdc_stone_svi_3;'...
           'else;'...
           'zdc_mtone_svi_3;'...
           'end;'...
           'set(VICTOGUI.htx,''string'', ''multiple simulation done, impedance results are saved'',''fontsize'',11);']);
       


VICTOGUI.h6=uicontrol(VICTOGUI.hVICTO,...
           'Style','pushbutton',...
           'unit','normalized',...
           'Position',[0.05, 0.15, 0.3, 0.05],...
           'Fontsize',12,'FontWeight','bold',...
           'String','Run all steps 1-3',...
           'backgroundcolor',[0.5586    0.7344    0.5586],...
           'Callback',...
           ['set(VICTOGUI.htx,''string'',''One button simulation running, wait for impedance to be plotted'',''fontsize'',11);'...
           'if (VICTOGUI.block_state==1)|(VICTOGUI.block_state==2);'...
           'zac_stone_sci_1;'...
           'zac_stone_sci_2;'...
           'VICTOGUI.perturbation_table=uitable(VICTOGUI.hVICTO,''RowName'',''P_frequencies(Hz)'',''Data'',VICTO.fit,''unit'',''normalized'',''Position'',[0.05, 0.61, 0.3, 0.09]);'...
           'zac_stone_sci_3;'...
           'elseif (VICTOGUI.block_state==3)|(VICTOGUI.block_state==4);'...
           'zac_mtone_sci_1;'...
           'zac_mtone_sci_2;'...
           'VICTOGUI.perturbation_table=uitable(VICTOGUI.hVICTO,''RowName'',''P_frequencies(Hz)'',''Data'',VICTO.fit,''unit'',''normalized'',''Position'',[0.05, 0.61, 0.3, 0.09]);'...
           'zac_mtone_sci_3;'...
           'elseif (VICTOGUI.block_state==5)|(VICTOGUI.block_state==6);'...
           'zac_stone_svi_1;'...
           'zac_stone_svi_2;'...
           'VICTOGUI.perturbation_table=uitable(VICTOGUI.hVICTO,''RowName'',''P_frequencies(Hz)'',''Data'',VICTO.fit,''unit'',''normalized'',''Position'',[0.05, 0.61, 0.3, 0.09]);'...
           'zac_stone_svi_3;'...
           'elseif (VICTOGUI.block_state==7)|(VICTOGUI.block_state==8);'...
           'zac_mtone_svi_1;'...
           'zac_mtone_svi_2;'...
           'VICTOGUI.perturbation_table=uitable(VICTOGUI.hVICTO,''RowName'',''P_frequencies(Hz)'',''Data'',VICTO.fit,''unit'',''normalized'',''Position'',[0.05, 0.61, 0.3, 0.09]);'...
           'zac_mtone_svi_3;'...
           'elseif VICTOGUI.block_state==9;'...
           'zdc_stone_sci_1;'...
           'zdc_stone_sci_2;'...
           'VICTOGUI.perturbation_table=uitable(VICTOGUI.hVICTO,''RowName'',''P_frequencies(Hz)'',''Data'',VICTO.fit,''unit'',''normalized'',''Position'',[0.05, 0.61, 0.3, 0.09]);'...
           'zdc_stone_sci_3;'...
           'elseif VICTOGUI.block_state==10;'...
           'zdc_mtone_sci_1;'...
           'zdc_mtone_sci_2;'...
           'VICTOGUI.perturbation_table=uitable(VICTOGUI.hVICTO,''RowName'',''P_frequencies(Hz)'',''Data'',VICTO.fit,''unit'',''normalized'',''Position'',[0.05, 0.61, 0.3, 0.09]);'...
           'zdc_mtone_sci_3;'...
           'elseif VICTOGUI.block_state==11;'...
           'zdc_stone_svi_1;'...
           'zdc_stone_svi_2;'...
           'VICTOGUI.perturbation_table=uitable(VICTOGUI.hVICTO,''RowName'',''P_frequencies(Hz)'',''Data'',VICTO.fit,''unit'',''normalized'',''Position'',[0.05, 0.61, 0.3, 0.09]);'...
           'zdc_stone_svi_3;'...
           'else;'...
           'zdc_mtone_svi_1;'...
           'zdc_mtone_svi_2;'...
           'VICTOGUI.perturbation_table=uitable(VICTOGUI.hVICTO,''RowName'',''P_frequencies(Hz)'',''Data'',VICTO.fit,''unit'',''normalized'',''Position'',[0.05, 0.61, 0.3, 0.09]);'...
           'zdc_mtone_svi_3;'...
           'end;'...
           'set(VICTOGUI.htx,''string'',''One button simulation done, impedance results are saved'',''fontsize'',11);']);


      
VICTOGUI.h7=uicontrol(VICTOGUI.hVICTO,...
           'Style','pushbutton',...
           'unit','normalized',...
           'Position',[0.05, 0.09, 0.3, 0.05],...
           'Fontsize',12,'FontWeight','bold',...
           'backgroundcolor',[0.8594    0.0781    0.2344],...
           'String','exit',...
           'Callback',...
           ['close(VICTOGUI.HFIG);'...
           'clear VICTOGUI;']);


    %Select second tab
    VICTOGUI.hstability = VICTOGUI.HSHEETPANELS(2);

     
    %Create axes for plots
    VICTOGUI.hACAxeses = zeros(1,4);
    for m = 1:4
        VICTOGUI.hACAxeses(m) = axes('Parent',VICTOGUI.hstability, 'Position',[0.45, 0.9-m*0.2, 0.5, 0.15]);
    end
    
    clear m;
    %Panels are like child windows.
VICTOGUI.hstex = uicontrol(VICTOGUI.hstability,...
                 'style','tex',...
                 'unit','normalized',...
                 'position',[0.45,0.9,0.5,0.06],...
                 'backgroundcolor',[0 0.8047 0.8164],...
                 'fontsize',11,'fontweight','bold',... 
                 'string','specify the impedance files and apply stability analysis');

VICTOGUI.hstex2 = uicontrol(VICTOGUI.hstability,...
                 'style','tex',...
                 'unit','normalized',...
                 'position',[0.05 0.03 0.3 0.06],...
                 'backgroundcolor',[0.8516 0.4375 0.8359],...
                 'fontsize',10,'fontweight','bold',... 
                 'string','           Stability Analysis Suite             Copyright © 2012 Boeing. All rights reserved.');


VICTOGUI.hlogo2=axes('Parent',VICTOGUI.hstability,'units','normalized','position',[0.05 0.75 0.3 0.25]);
uistack(VICTOGUI.hlogo2,'down');
VICTOGUI.logo2=imread('Stability.png');
image(VICTOGUI.logo2)
colormap gray
set(VICTOGUI.hlogo2,'handlevisibility','off','visible','off');             

 VICTOGUI.hmode_raw = uicontrol(VICTOGUI.hstability,'style','radio',...
                 'units','normalized',...
                 'position',[0.05, 0.7, 0.3, 0.05],...
                 'backgroundcolor',[1.0000    1.0000    0.9375],...
                 'Value', 0,...
                 'string','Raw data analysis','Fontsize',11,'FontAngle','italic',...
                 'Callback',...
                 ['set(VICTOGUI.hmode_average,''Value'', 0);'...
                  'set(VICTOGUI.hmode_raw,''Value'', 1);'...
                  'VICTOGUI.raw_analysis=1;']);
VICTOGUI.hmode_average = uicontrol(VICTOGUI.hstability,'style','radio',...
                 'units','normalized',...
                 'position',[0.05, 0.65, 0.3, 0.05],...
                 'backgroundcolor',[1.0000    1.0000    0.9375],...
                 'Value', 0,...
                 'string','Smoothed data analysis','Fontsize',11,'FontAngle','italic',...
                 'Callback',...
                 ['set(VICTOGUI.hmode_raw,''Value'', 0);'...
                  'set(VICTOGUI.hmode_average,''Value'', 1);'...
                  'VICTOGUI.raw_analysis=0;']);

             
VICTOGUI.hspecifysource=uicontrol(VICTOGUI.hstability,...
           'Style','pushbutton',...
           'unit','normalized',...
           'Position',[0.05, 0.58, 0.3, 0.05],...
           'String','specify source impedance file','Fontsize',12,'FontWeight','bold',...
           'Callback',...
           ['[VICTOGUI.source_impedance_name1, VICTOGUI.source_impedance_path1]=uigetfile(''*.mat'',''Select source impedance file'');'...
           'VICTOGUI.source_impedance_str=[VICTOGUI.source_impedance_path1, VICTOGUI.source_impedance_name1];'...
           'load(VICTOGUI.source_impedance_str);'...
           'if strcmp(Z.Type,''AC'');'...
           'VICTOGUI.Ztype=''AC'';'...
           'if strcmp(Z.Target,''Source&Load'');'...
           'if (''VICTOGUI.raw_analysis==0'');'...
           'VICTOGUI.ZplotDQS=Z.ZDQS;'...
           'else;'...
           'VICTOGUI.ZplotDQS=Z.ZDQSRAW;'...
           'end;'...
           'set(VICTOGUI.hstex,''string'',''The source impedance is from VICTO'');'...
           'elseif strcmp(Z.Target,''Source'');'...
           'if (''VICTOGUI.raw_analysis==0'');'...
           'VICTOGUI.ZplotDQS=Z.ZDQ;'...
           'else;'...
           'VICTOGUI.ZplotDQS=Z.ZDQRAW;'...
           'end;'...
           'set(VICTOGUI.hstex,''string'',''The source impedance is from impedance analyzer'');'...
           'else;'...
           'set(VICTOGUI.hstex,''string'',''ERROR: you specified a load impedance file!'');'...
           'end;'...
           'else;'...
           'VICTOGUI.Ztype=''DC'';'...
           'if strcmp(Z.Target,''Source&Load'');'...
           'if (''VICTOGUI.raw_analysis==0'');'...
           'VICTOGUI.ZplotDCS=Z.ZDCS;'...
           'else;'...
           'VICTOGUI.ZplotDCS=Z.ZDCSRAW;'...
           'end;'...
           'set(VICTOGUI.hstex,''string'',''The source impedance is from VICTO'');'...
           'elseif strcmp(Z.Target,''Source'');'...
           'if (''VICTOGUI.raw_analysis==0'');'...
           'VICTOGUI.ZplotDCS=Z.ZDC;'...
           'else;'...
           'VICTOGUI.ZplotDCS=Z.ZDCRAW;'...
           'end;'...
           'set(VICTOGUI.hstex,''string'',''The source impedance is from impedance analyzer'');'...
           'else;'...
           'set(VICTOGUI.hstex,''string'',''ERROR: you specified a load impedance file!'');'...
           'end;'...
           'end;'...
           'clear Z;'...
           'AutoZplotS';]);       
    
VICTOGUI.hspecifyload=uicontrol(VICTOGUI.hstability,...
           'Style','pushbutton',...
           'unit','normalized',...
           'Position',[0.05, 0.52, 0.3, 0.05],...
           'String','specify load impedance file','Fontsize',12,'FontWeight','bold',...
           'Callback',...
           ['[VICTOGUI.load_impedance_name1 VICTOGUI.load_impedance_path1]=uigetfile(''*.mat'',''Select load impedance file'');'...
           'VICTOGUI.load_impedance_str=[VICTOGUI.load_impedance_path1, VICTOGUI.load_impedance_name1];'...
           'load(VICTOGUI.load_impedance_str);'...
           'if strcmp(Z.Type,''AC'');'...
           'VICTOGUI.Ztype=''AC'';'...
           'if strcmp(Z.Target,''Source&Load'');'...
           'if (''VICTOGUI.raw_analysis==0'');'...
           'VICTOGUI.ZplotDQL=Z.ZDQL;'...
           'else;'...
           'VICTOGUI.ZplotDQL=Z.ZDQLRAW;'...
           'end;'...
           'set(VICTOGUI.hstex,''string'',''The load impedance is from VICTO'');'...
           'elseif strcmp(Z.Target,''Load'');'...
           'if (''VICTOGUI.raw_analysis==0'');'...
           'VICTOGUI.ZplotDQL=Z.ZDQ;'...
           'else;'...
           'VICTOGUI.ZplotDQL=Z.ZDQRAW;'...
           'end;'...
           'set(VICTOGUI.hstex,''string'',''The load impedance is from impedance analyzer'');'...
           'else;'...
           'set(VICTOGUI.hstex,''string'',''ERROR: you specified a source impedance file!'');'...
           'end;'...
           'else;'...
           'VICTOGUI.Ztype=''DC'';'...
           'if strcmp(Z.Target,''Source&Load'');'...
           'if (''VICTOGUI.raw_analysis==0'');'...
           'VICTOGUI.ZplotDCL=Z.ZDCL;'...
           'else;'...
           'VICTOGUI.ZplotDCL=Z.ZDCLRAW;'...
           'end;'...
           'set(VICTOGUI.hstex,''string'',''The load impedance is from VICTO'');'...
           'elseif strcmp(Z.Target,''Load'');'...
           'if (''VICTOGUI.raw_analysis==0'');'...
           'VICTOGUI.ZplotDCL=Z.ZDC;'...
           'else;'...
           'VICTOGUI.ZplotDCL=Z.ZDCRAW;'...
           'end;'...
           'set(VICTOGUI.hstex,''string'',''The load impedance is from impedance analyzer'');'...
           'else;'...
           'set(VICTOGUI.hstex,''string'',''ERROR: you specified a source impedance file!'');'...
           'end;'...
           'end;'...
           'clear Z;'...
           'AutoZplotL';]);       

VICTOGUI.hgnc=uicontrol(VICTOGUI.hstability,...
           'Style','pushbutton',...
           'unit','normalized',...
           'Position',[0.05, 0.46, 0.3, 0.05],...
           'Fontsize',12,'FontWeight','bold',...
           'String','Generalized Nyquist Criterion Analysis',...
           'Callback',...
           'GNC_plot');
  
VICTOGUI.hsgnc=uicontrol(VICTOGUI.hstability,...
           'Style','pushbutton',...
           'unit','normalized',...
           'Position',[0.05, 0.40, 0.3, 0.05],...
           'Fontsize',12,'FontWeight','bold',...
           'String','Simplified GNC Analysis',...
           'Callback',...
           'SNC_plot');
       
VICTOGUI.hsiso=uicontrol(VICTOGUI.hstability,...
           'Style','pushbutton',...
           'unit','normalized',...
           'Position',[0.05, 0.34, 0.3, 0.05],...
           'Fontsize',12,'FontWeight','bold',...
           'String','SISO Nyquist Criterion Analysis',...
           'Callback',...
           'SISO_plot');
       
VICTOGUI.nACMultipleplot=0;
VICTOGUI.nDCMultipleplot=0;

VICTOGUI.hmultiple1=uicontrol(VICTOGUI.hstability,...
           'Style','pushbutton',...
           'unit','normalized',...
           'Position',[0.05, 0.28, 0.3, 0.05],...
           'Fontsize',12,'FontWeight','bold',...
           'String','Specify AC multi-plot impedance',...
           'Callback',...
           ['VICTOGUI.nACMultipleplot=VICTOGUI.nACMultipleplot+1;'...
            'VICTOGUI.multiple_impedance_name1=uigetfile(''*.mat'',''Select impedance file for multiple-plot analysis'');'...
            'VICTOGUI.ac_multiple_impedance_str(:,:,VICTOGUI.nACMultipleplot)=cellstr(VICTOGUI.multiple_impedance_name1);']);
        
VICTOGUI.hmultiple2=uicontrol(VICTOGUI.hstability,...
           'Style','pushbutton',...
           'unit','normalized',...
           'Position',[0.05, 0.22, 0.3, 0.05],...
           'Fontsize',12,'FontWeight','bold',...
           'String','Specify DC multi-plot impedance',...
           'Callback',...
           ['VICTOGUI.nDCMultipleplot=VICTOGUI.nDCMultipleplot+1;'...
            'VICTOGUI.multiple_impedance_name1=uigetfile(''*.mat'',''Select impedance file for multiple-plot analysis'');'...
            'VICTOGUI.dc_multiple_impedance_str(:,:,VICTOGUI.nDCMultipleplot)=cellstr(VICTOGUI.multiple_impedance_name1);']);
       
VICTOGUI.hmultiple3=uicontrol(VICTOGUI.hstability,...
           'Style','pushbutton',...
           'unit','normalized',...
           'Position',[0.05, 0.16, 0.3, 0.05],...
           'Fontsize',12,'FontWeight','bold',...
           'String','Multiple Impedance Plot Analysis',...
           'Callback',...
           'Multiple_impedace_plot');
        
VICTOGUI.hexit=uicontrol(VICTOGUI.hstability,...
           'Style','pushbutton',...
           'unit','normalized',...
           'Position',[0.05, 0.10, 0.3, 0.05],...
           'Fontsize',12,'FontWeight','bold',...
           'backgroundcolor',[0.8594    0.0781    0.2344],...
           'String','exit',...
           'Callback',...
           ['close(VICTOGUI.HFIG);'...
           'clear VICTOGUI;']);
       
       %%%default tab selection: Tab 1
 set(VICTOGUI.HSHEETPANELS(1), 'Visible', 'on');
 set(VICTOGUI.HSHEETPANELS(2), 'Visible', 'off');